"""empty message

Revision ID: 006bacfe2be2
Revises: 4dc3fb909992
Create Date: 2020-07-09 12:15:04.239839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006bacfe2be2'
down_revision = '4dc3fb909992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
