"""Added missing columns

Revision ID: 4dc3fb909992
Revises: 13bd4d88bcf5
Create Date: 2020-07-08 23:44:43.675795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dc3fb909992'
down_revision = '13bd4d88bcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_constraint('Artist_image_link_key', 'Artist', type_='unique')
    op.drop_constraint('Artist_name_key', 'Artist', type_='unique')
    op.alter_column('Show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_constraint('Venue_name_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_name_key', 'Venue', ['name'])
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'genres')
    op.alter_column('Show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint('Artist_name_key', 'Artist', ['name'])
    op.create_unique_constraint('Artist_image_link_key', 'Artist', ['image_link'])
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
